inherit_from: .rubocop_todo.yml

require: rubocop

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Layout/LineLength:
  Enabled: false

# "Block has too many lines"を無効
Metrics/BlockLength:
  Enabled: false

# "Method has too many lines"を無効
Metrics/MethodLength:
  Enabled: false

# Use nested module/class definitions instead of compact style. を無効
Style/ClassAndModuleChildren:
  Enabled: false

# ABC Sizeの許容値を40へ(デフォルトは15)
Metrics/AbcSize:
  Enabled: true
  Max: 40

Style/HashEachMethods:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false
#inherit_gem:
#  rubocop-config-rufo: rubocop.yml
